### ISSUE TITLE
how to use in vue touer?

### ISSUE THREAD

**Issue by StringKe** [sindresorhus/electron-serve#9]
https://github.com/SimulatedGREG/electron-vue

**Comment by sindresorhus** [comment]
I don't use Vue and cannot provide info how to integrate it with any kind of boilerplate solution. This module serves the files as if they were served by a server and not `file://`, which enables actually changing the URL instead of using hash. How to integrate it into `electron-vue` is really up to you to figure out. You could try asking on the `electron-vue` issue tracker.
